site: UDS

url: https://uds-rnd.github.io/
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /sfoasnfonsdzisfiuaoheufaougfuaweelubfuzsdygyfaegew/:slug
    type: "post"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

jekyll_admin: 
  hidden_links:
    - _posts
  homepage: "_posts"

markdown: kramdown
highlighter: rouge

kramdown:
  html_to_native: true
  math_engine: KaTeX
  sinput: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'

mermaid:
  src: 'path/to/mermaid.js'