basic_settings:
  site_title: Utopia Data Systems
  favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/brand/uds.png
  mobile_logo_image: /assets/img/brand/uds.png
  # Choose a color for your header [blue, dark, light, transparent].
  theme: transparent
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: 'yes'

home_settings:
  # Choose a layout for your home page:
  # landing – an example landing page made using the Argon design system
  # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
  # basic – a simple list of posts
  # narrow – a masonary grid of posts
  # grid – a full-width square grid of posts
  theme: basic
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: 'no'

# Setup your navigation below – how to use the icons:
# 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
# 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket.
# 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work!
menu_settings:
  menu_items:
    - title: 'Home'
      url: /
    - title: 'Solutions'
      submenu_items:
        - title: SBMS
          url: /sbms
          icon: ni-books text-info
        - title: QMS
          url: /qms
          icon: ni-folder-17 text-info
        - title: Udap
          url: /udap
          icon: ni-sound-wave text-info
    - title: 'Blog'
      url: /login
    - title: 'About'
      url: /about
    - title: 'Recruit'
      url: /recruit
    - title: 'Contact'
      url: /contact

footer_settings:
  footer_tagline: Utopia Data Systems

contact_settings:
  form_action: 'https://formspree.io/f/xleajenz'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: 'https://www.youtube.com/watch?v=hX1BeCMLCS4&feature=emb_logo'
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: ''
  reddit_url: ''
  linkedin_url: ''

authors:
  sean:
    name: Sean
    picture: /assets/img/faces/team-6.jpg
  tom:
    name: Garfield
    picture: /assets/img/faces/garfield.jpg
  UDS:
    name: UDS
    picture: /assets/img/faces/default.jpg
    
advanced_settings:
  analytics_code:
  header_js:
  footer_js:
